// Deploys MockUSDT + PayPort on X Layer and seeds sample payment links.
//   npx hardhat run scripts/deploy.js --network xlayerTestnet
const { existsSync, readFileSync, writeFileSync, mkdirSync } = require("node:fs");
const { join, dirname } = require("node:path");
const { JsonRpcProvider, Wallet, ContractFactory, formatUnits } = require("ethers");
const { readEnvValue } = require("./read-env");

const CHAIN_ID = Number(process.env.DEPLOY_CHAIN_ID || 1952);
const RPC_URL =
  CHAIN_ID === 196 ? "https://rpc.xlayer.tech" : "https://testrpc.xlayer.tech/terigon";
const NETWORK_LABEL = CHAIN_ID === 196 ? "X Layer Mainnet (chain 196)" : "X Layer Testnet (chain 1952)";
const EXPLORER = "https://www.okx.com/web3/explorer/xlayer" + (CHAIN_ID === 196 ? "" : "-test");

const payportArtifactPath = join(__dirname, "..", "artifacts", "contracts", "PayPort.sol", "PayPort.json");
const mockUsdtArtifactPath = join(__dirname, "..", "artifacts", "contracts", "MockUSDT.sol", "MockUSDT.json");

const seedLinks = [
  { slug: "arcade-run-001", title: "Arcade Run 001", priceUsdCents: 25 },
  { slug: "studio-retainer-july", title: "July studio retainer", priceUsdCents: 10 },
  { slug: "archive-print-release", title: "Archive print release", priceUsdCents: 5 },
];

async function deploy(wallet, artifactPath, args) {
  const artifact = JSON.parse(readFileSync(artifactPath, "utf8"));
  const factory = new ContractFactory(artifact.abi, artifact.bytecode, wallet);
  const contract = await factory.deploy(...args);
  await contract.waitForDeployment();
  return contract;
}

async function main() {
  const key = readEnvValue("DEPLOYER_PRIVATE_KEY");

  if (!key) {
    throw new Error("No DEPLOYER_PRIVATE_KEY. Run: node scripts/new-wallet.js");
  }

  if (!existsSync(payportArtifactPath) || !existsSync(mockUsdtArtifactPath)) {
    throw new Error("No compiled artifacts. Run: npx hardhat compile");
  }

  const provider = new JsonRpcProvider(RPC_URL, CHAIN_ID);
  const wallet = new Wallet(key, provider);
  const balance = await provider.getBalance(wallet.address);

  console.log("Network:  " + NETWORK_LABEL);
  console.log("Deployer: " + wallet.address);
  console.log("Balance:  " + formatUnits(balance, 18) + " OKB");

  if (balance === 0n) {
    throw new Error(
      "Deployer has no testnet OKB. Claim gas at https://web3.okx.com/xlayer/faucet/xlayerfaucet for " +
        wallet.address,
    );
  }

  let usdtAddress = readEnvValue("USDT_ADDRESS");

  if (usdtAddress) {
    console.log("");
    console.log("Using existing USDT at " + usdtAddress);
  } else {
    console.log("");
    console.log("Deploying MockUSDT...");
    const usdt = await deploy(wallet, mockUsdtArtifactPath, []);
    usdtAddress = await usdt.getAddress();
    console.log("MockUSDT: " + EXPLORER + "/address/" + usdtAddress);

    const faucetTx = await usdt.faucet();
    await faucetTx.wait();
    console.log("Fauceted 1,000 USDT to the deployer for demo payments.");
  }

  console.log("");
  console.log("Deploying PayPort...");

  const payPort = await deploy(wallet, payportArtifactPath, [usdtAddress]);
  const address = await payPort.getAddress();
  const deployTx = payPort.deploymentTransaction();

  console.log("PayPort:  " + address);
  console.log("Tx:       " + EXPLORER + "/tx/" + deployTx.hash);

  console.log("");
  console.log("Seeding payment links...");

  for (const link of seedLinks) {
    const tx = await payPort.createPaymentLink(link.slug, link.title, link.priceUsdCents, 0);
    await tx.wait();

    const [requiredToken] = await payPort.quoteToken(link.slug);
    console.log(
      "  " +
        link.slug.padEnd(24) +
        "$" +
        (link.priceUsdCents / 100).toFixed(2).padStart(9) +
        "  =  " +
        Number(formatUnits(requiredToken, 6)).toFixed(2) +
        " USDT",
    );
  }

  const outPath = join(__dirname, "..", "..", "src", "lib", "contract-address.ts");
  mkdirSync(dirname(outPath), { recursive: true });

  writeFileSync(
    outPath,
    "// Generated by contracts/scripts/deploy.js. Do not edit by hand.\n" +
      "// Deployed " +
      new Date().toISOString() +
      " to " +
      NETWORK_LABEL +
      ".\n\n" +
      "export const PAYPORT_ADDRESS =\n  \"" +
      address +
      "\" as const;\n\n" +
      "export const SETTLEMENT_TOKEN_ADDRESS =\n  \"" +
      usdtAddress +
      "\" as const;\n\n" +
      "export const DEMO_SLUG = \"" +
      seedLinks[0].slug +
      "\" as const;\n",
    "utf8",
  );

  console.log("");
  console.log("Wrote addresses to src/lib/contract-address.ts");
}

main().catch((error) => {
  console.error(error.message || error);
  process.exitCode = 1;
});
