// Seeds payment links on an already-deployed PayPort and writes contract-address.ts.
const { readFileSync, writeFileSync, mkdirSync } = require("node:fs");
const { join, dirname } = require("node:path");
const { JsonRpcProvider, Wallet, Contract } = require("ethers");
const { readEnvValue } = require("./read-env");

const CHAIN_ID = 1952;
const RPC_URL = "https://testrpc.xlayer.tech/terigon";

const PAYPORT_ADDRESS = process.env.PAYPORT_ADDRESS;
const USDT_ADDRESS = process.env.USDT_ADDRESS;

const seedLinks = [
  { slug: "arcade-run-001", title: "Arcade Run 001", priceUsdCents: 25 },
  { slug: "studio-retainer-july", title: "July studio retainer", priceUsdCents: 10 },
  { slug: "archive-print-release", title: "Archive print release", priceUsdCents: 5 },
];

async function withRetry(fn, label) {
  for (let attempt = 1; attempt <= 5; attempt++) {
    try {
      return await fn();
    } catch (error) {
      const msg = String(error.message || error);
      const benign = /SlugTaken/i.test(msg);
      if (benign) return null;
      if (attempt === 5) throw error;
      console.log(`  ${label} failed (${msg.slice(0, 60)}), retry ${attempt}/5...`);
      await new Promise((r) => setTimeout(r, 3000 * attempt));
    }
  }
}

async function main() {
  if (!PAYPORT_ADDRESS || !USDT_ADDRESS) {
    throw new Error("Set PAYPORT_ADDRESS and USDT_ADDRESS env vars.");
  }

  const key = readEnvValue("DEPLOYER_PRIVATE_KEY");
  if (!key) throw new Error("No DEPLOYER_PRIVATE_KEY.");

  const artifact = JSON.parse(
    readFileSync(join(__dirname, "..", "artifacts", "contracts", "PayPort.sol", "PayPort.json"), "utf8"),
  );

  const provider = new JsonRpcProvider(RPC_URL, CHAIN_ID, { staticNetwork: true });
  provider.pollingInterval = 2000;
  const wallet = new Wallet(key, provider);
  const payPort = new Contract(PAYPORT_ADDRESS, artifact.abi, wallet);

  async function tryGetLink(slug) {
    for (let attempt = 1; attempt <= 6; attempt++) {
      try {
        return await payPort.getPaymentLink(slug);
      } catch (error) {
        if (/UnknownLink/i.test(String(error))) return null;
        if (attempt === 6) throw error;
        await new Promise((r) => setTimeout(r, 3000 * attempt));
      }
    }
    return null;
  }

  for (const link of seedLinks) {
    const existing = await tryGetLink(link.slug);
    if (existing && existing.merchant !== "0x0000000000000000000000000000000000000000") {
      console.log(`  ${link.slug} already exists, skipping.`);
      continue;
    }

    const result = await withRetry(async () => {
      const tx = await payPort.createPaymentLink(link.slug, link.title, link.priceUsdCents, 0);
      await tx.wait();
      return true;
    }, `create ${link.slug}`);

    if (result) {
      const [requiredToken] = await payPort.quoteToken(link.slug);
      console.log(
        `  ${link.slug.padEnd(24)}$${(link.priceUsdCents / 100).toFixed(2).padStart(6)} = ${Number(requiredToken) / 1e6} USDT`,
      );
    }
  }

  const outPath = join(__dirname, "..", "..", "src", "lib", "contract-address.ts");
  mkdirSync(dirname(outPath), { recursive: true });

  writeFileSync(
    outPath,
    "// Generated by contracts/scripts/deploy.js. Do not edit by hand.\n" +
      "// Deployed " +
      new Date().toISOString() +
      " to X Layer Testnet (chain 1952).\n\n" +
      "export const PAYPORT_ADDRESS =\n  \"" +
      PAYPORT_ADDRESS +
      "\" as const;\n\n" +
      "export const SETTLEMENT_TOKEN_ADDRESS =\n  \"" +
      USDT_ADDRESS +
      "\" as const;\n\n" +
      "export const DEMO_SLUG = \"arcade-run-001\" as const;\n",
    "utf8",
  );

  console.log("Wrote addresses to src/lib/contract-address.ts");

  const balance = await payPort.quoteToken("arcade-run-001");
  console.log("Quote check arcade-run-001:", Number(balance[0]) / 1e6, "USDT");
}

main().catch((error) => {
  console.error(error.message || error);
  process.exitCode = 1;
});
