// Generated by contracts/scripts/deploy.js. Do not edit by hand.
// Deployed to X Layer Testnet (chain 1952). Settlement rail: Circle native USDC.

export const PAYPORT_ADDRESS =
  "0x8E29beF64b0a357A5C31ea36736c2f9f5541b431" as const;

export const SETTLEMENT_TOKEN_ADDRESS =
  "0xDec90b78111Ba2fc6FC6d84d8B9ec159A2d4b9B3" as const;

export const DEMO_SLUG = "arcade-run-001" as const;
